### ISSUE TITLE
目前是否支持7z分卷压缩的恢复文件密码

### ISSUE THREAD

**Issue by hifuclub** [jiangxincode/ApkToolBoxGUI#101]
比如说7z.001, 7z.002的分卷格式

另外希望可以对找到的密码进行复制操作

**Comment by jiangxincode** [comment]
> 比如说7z.001, 7z.002的分卷格式

已在该提交中增加分卷7z格式的文件密码恢复：https://github.com/jiangxincode/ApkToolBoxGUI/commit/643e76d2e5b118d01191d6a86d36dc63374db0b5

> 另外希望可以对找到的密码进行复制操作

已在该提交中增加复制密码的功能：https://github.com/jiangxincode/ApkToolBoxGUI/commit/eed94d5c694143a24abd9f4cf8196ff6f7a05b27
