### ISSUE TITLE
颜色拾取器显示方式

### ISSUE THREAD

**Issue by CDTDaily** [jiangxincode/ApkToolBoxGUI#146]
你好，请问HSB模式下能否以数值255的格式显示

**Comment by jiangxincode** [comment]
HSB的本身的通用表示是H [0, 360]或者[0 1]，S[0 1]，B[0 1]
你可以通过维基百科做进一步了解：
https://zh.wikipedia.org/wiki/HSL%E5%92%8CHSV%E8%89%B2%E5%BD%A9%E7%A9%BA%E9%97%B4
