### ISSUE TITLE
密码恢复功能建议继续完善

### ISSUE THREAD

**Issue by itspidercn** [jiangxincode/ApkToolBoxGUI#337]
对照最经典的ARCHPR，多线程的设计非常棒，提速明显，先赞一个！
但使用中发现一些问题，建议完善，优先级从高到低如下：
1、增加进度保存功能，否则解密过程中，一不小心就得重来一次，比如试用一下其他功能，再回来进度就得从头来。
2、暴力破解，建议增加掩码位和自定义字符集的功能，最好能允许每一位都能自行设置。
3、最大位长，现在只能是9，在上面第2条功能实现后，这个位长希望能突破10
4、进度条之外，增加破解速度显示，动态显示每秒多少个密码。现在底行的Typing处，变化太快根本看不清，可以考虑跟破解速度一起每秒一变。
谢谢！

**Comment by jiangxincode** [comment]
你好，欢迎你的建议，其中第2条定义功能已在该提交中增加：https://github.com/jiangxincode/ApkToolBoxGUI/commit/a69bf2b92397811e624f306bb1889a7b53ab88a3
其它功能后续会考虑增加，请持续关注。

**Comment by itspidercn** [comment]
> 你好，欢迎你的建议，其中第2条定义功能已在该提交中增加：[2de363e](https://github.com/jiangxincode/ApkToolBoxGUI/commit/2de363ee773ddbe19fcd43d113bba9c07c26d1a7) 但是我暂时没有想到每一位支持掩码或者自定义的必要性，这种好像没有实际使用场景，所以我加的是全局掩码和自定义字符。 其它功能后续会考虑增加，请持续关注。

可能我没说清楚，举几个例子吧，假设密码总位长4位
例1：每位都是单字符
Position1：0123456789
Position2：0123456789+-=
Position3：0123456789abcdefghjklmnpqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ     ——注意：字母中没有i和I、o和O
Position4：.@#$%^$%^&0123456789

例2：允许每位是多字符的字串（用回车键分隔）,但4位组合后的字串用总位长来截短，实用场景一般总位长会比较大。
Position1：
      http://
      https://      
      ftp://
Position2：
      www.
      oa.
      mail.
Position3：
      xxx.com
      xxx.com.cn
      xxx.org
Position4：
      /
      /login

**Comment by jiangxincode** [comment]
第4条显示恢复速度功能已经在如下链接中增加：https://github.com/jiangxincode/ApkToolBoxGUI/commit/e8213e45f09042888f3caf2e6142712b0d89be7e

**Comment by jiangxincode** [comment]
第1条增加保存功能还比较困难，但是切换到其它界面再返回需要重头再来的问题，已经在如下链接中增加：https://github.com/jiangxincode/ApkToolBoxGUI/commit/fde040c63301141dba079ade8c921db4108a8c1e
