### ISSUE TITLE
mac  big sur 11.1 下运行报错

### ISSUE THREAD

**Issue by TheJokerW** [jiangxincode/ApkToolBoxGUI#44]
![image](https://user-images.githubusercontent.com/36848313/137062024-bd6dc9a8-2e2c-4a8c-bd7b-e9ce7cd2779c.png)

**Comment by jiangxincode** [comment]
这个可能是因为Mac系统和其它系统有所区别，没有处理好。我这边暂时没有Mac机器，暂时会先装个虚拟机尝试复现下，如果你有能力和时间的话可以先看下能否定位提个patch，如果OK的话我会尽快合入。

**Comment by jiangxincode** [comment]
这个问题已经修复，请使用最新代码编译

**Comment by TheJokerW** [comment]
> 这个问题已经修复，请使用最新代码编译

好的 辛苦作者

**Comment by TheJokerW** [comment]
> > 这个问题已经修复，请使用最新代码编译
> 
> 好的 已用最新代码构建成功 辛苦作者
