### ISSUE TITLE
构建时依赖仓库地址失效

### ISSUE THREAD

**Issue by TheJokerW** [jiangxincode/ApkToolBoxGUI#45]
![image](https://user-images.githubusercontent.com/36848313/137268535-94765aec-9d9f-4da2-b010-8a699f959e74.png)

**Comment by jiangxincode** [comment]
已经将依赖上传到Maven中心仓库，并修改了pom.xml，此时应该不会有该问题，暂时关闭此issue，有问题可以继续反馈
