### ISSUE TITLE
恢复文件密码功能找到的密码无法进行选中复制操作

### ISSUE THREAD

**Issue by coofo** [jiangxincode/ApkToolBoxGUI#95]
有的密码会很长而且包括一些容易混淆的字符，希望最后显示密码的地方可以对找到的密码进行复制操作

**Comment by jiangxincode** [comment]
最近会修复这个问题，可能不再以弹窗方式提示用户结果，而是在主界面增加一个结果展示区域

**Comment by jiangxincode** [comment]
已在该提交中增加复制密码的功能：https://github.com/jiangxincode/ApkToolBoxGUI/commit/eed94d5c694143a24abd9f4cf8196ff6f7a05b27
